import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import {
    ArrowLeft, Loader2, MessageSquare, Star,
    Bot, Copy, Check, Sparkles, Wand2, History as HistoryIcon,
    Trash2, Search, Filter, Languages, Smartphone, ShieldCheck
} from 'lucide-react';
import { generateAutoReply } from '@/services/gemini';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import { LanguageToggle } from '@/components/LanguageToggle';

interface Review {
    id: string;
    rating: number;
    review_text: string | null;
    customer_name: string | null;
    created_at: string;
    auto_reply_text?: string | null;
    metadata?: any;
}

export default function ReviewManagement() {
    const navigate = useNavigate();
    const { t, i18n } = useTranslation();
    const [reviews, setReviews] = useState<Review[]>([]);
    const [loading, setLoading] = useState(true);
    const [generatingFor, setGeneratingFor] = useState<string | null>(null);

    useEffect(() => {
        fetchReviews();
    }, []);

    const fetchReviews = async () => {
        try {
            setLoading(true);
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            const { data, error } = await (supabase as any)
                .from('analytics_logs')
                .select('*')
                .eq('event_type', 'review_click')
                .order('created_at', { ascending: false });

            if (error) throw error;

            const formattedReviews = data.map((item: any) => ({
                id: item.id,
                rating: item.metadata?.rating || 5,
                review_text: item.metadata?.suggestion || 'Positive review generated by AI',
                customer_name: 'Customer',
                created_at: item.created_at,
                auto_reply_text: item.metadata?.auto_reply,
                metadata: item.metadata
            }));

            setReviews(formattedReviews);
        } catch (error) {
            console.error('Error fetching reviews:', error);
            toast.error('Failed to load reviews');
        } finally {
            setLoading(false);
        }
    };

    const handleGenerateReply = async (review: Review) => {
        setGeneratingFor(review.id);
        try {
            const reply = await generateAutoReply(
                review.review_text || 'Excellent service',
                review.rating,
                'Our Business',
                i18n.language
            );

            await (supabase as any)
                .from('analytics_logs')
                .update({
                    metadata: {
                        ...review.metadata,
                        auto_reply: reply
                    }
                })
                .eq('id', review.id);

            toast.success('AI Auto-Reply Generated!');
            setReviews(prev => prev.map(r => r.id === review.id ? { ...r, auto_reply_text: reply } : r));
        } catch (error) {
            console.error('Reply generation failed:', error);
            toast.error('Failed to generate reply');
        } finally {
            setGeneratingFor(null);
        }
    };

    const handleCopy = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success('Copied to clipboard!');
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-white font-inter">
                <Loader2 className="h-16 w-16 animate-spin text-red-600" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white font-inter pb-40 relative overflow-hidden">
            {/* Background Decor */}
            <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-red-50/50 rounded-full blur-[150px] -z-10 translate-x-1/2 -translate-y-1/2"></div>

            {/* Premium Header - Large Logo */}
            <header className="bg-white/90 backdrop-blur-xl border-b border-gray-100 sticky top-0 z-50 shadow-sm">
                <div className="container mx-auto px-8 py-8 flex items-center justify-between">
                    <div className="flex items-center gap-10">
                        <Button variant="ghost" size="icon" onClick={() => navigate("/dashboard")} className="hover:bg-red-50 text-gray-400 hover:text-red-600 h-16 w-16 rounded-2xl transition-all">
                            <ArrowLeft className="h-8 w-8" />
                        </Button>
                        <div className="flex items-center gap-6 group">
                            <div className="bg-red-600 p-5 rounded-[1.5rem] shadow-2xl group-hover:rotate-12 transition-all">
                                <Bot className="h-8 w-8 text-white" />
                            </div>
                            <div className="hidden lg:block">
                                <h1 className="text-3xl font-black text-gray-950 tracking-tighter uppercase italic leading-none">AI Auto-Reply Hub</h1>
                                <p className="text-[10px] font-black text-red-600 uppercase tracking-[0.4em] mt-2 italic leading-none">Response Protocol</p>
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <img src="/logo.jpg" alt="Logo" className="h-20 w-auto object-contain rounded-2xl shadow-2xl transition-all hover:scale-110" />
                    </div>
                </div>
            </header>

            <main className="container mx-auto px-8 py-20 max-w-7xl">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-10 mb-20 border-l-[12px] border-red-600 pl-16 py-4">
                    <div>
                        <h2 className="text-6xl font-black text-gray-950 uppercase tracking-tighter italic leading-none mb-4">Sentiment Analysis</h2>
                        <p className="text-sm font-black text-gray-400 uppercase tracking-[0.4em] italic leading-none">Generate professional AI responses for verified reviews</p>
                    </div>
                    <div className="flex items-center gap-6 w-full md:w-auto">
                        <Button variant="outline" className="flex-1 md:flex-none h-16 px-10 border-2 border-gray-100 rounded-[1.5rem] font-black uppercase tracking-[0.3em] text-xs hover:border-red-600 hover:text-red-600 transition-all shadow-sm">
                            <Search className="h-5 w-5 mr-3" />
                            Search
                        </Button>
                        <Button onClick={fetchReviews} className="flex-1 md:flex-none bg-red-600 hover:bg-black text-white rounded-[1.5rem] h-16 px-10 shadow-[0_30px_60px_-10px_rgba(220,38,38,0.3)] font-black uppercase tracking-[0.3em] text-xs transition-all">
                            <Wand2 className="h-5 w-5 mr-3" />
                            Sync Fleet
                        </Button>
                    </div>
                </div>

                <div className="grid grid-cols-1 gap-12">
                    {reviews.length === 0 ? (
                        <Card className="border-8 border-dashed border-gray-50 rounded-[5rem] py-56 text-center bg-transparent group hover:border-red-100 transition-all duration-1000">
                            <div className="flex flex-col items-center gap-10 opacity-10 group-hover:opacity-30 transition-opacity">
                                <MessageSquare className="h-32 w-32" />
                                <p className="font-black uppercase tracking-[0.8em] text-xs">No intercepted transmissions</p>
                            </div>
                        </Card>
                    ) : (
                        reviews.map((review) => (
                            <Card key={review.id} className="border-0 shadow-4xl rounded-[5rem] overflow-hidden bg-white hover:shadow-red-500/10 transition-all duration-700 animate-in fade-in slide-in-from-bottom-10 group">
                                <div className="h-4 bg-red-600 w-0 group-hover:w-full transition-all duration-1000"></div>
                                <CardContent className="p-16">
                                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-20">
                                        {/* Left: Customer Review Info */}
                                        <div className="space-y-10">
                                            <div className="flex items-center justify-between">
                                                <div className="flex items-center gap-6">
                                                    <div className="w-16 h-16 bg-gray-50 rounded-[1.5rem] flex items-center justify-center font-black text-gray-300 text-xl border border-gray-100 shadow-inner">
                                                        U
                                                    </div>
                                                    <div>
                                                        <p className="font-black text-gray-950 uppercase tracking-tighter text-2xl italic leading-none mb-2">Verified Satellite Link</p>
                                                        <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.4em] italic leading-none">{new Date(review.created_at).toLocaleString()}</p>
                                                    </div>
                                                </div>
                                                <div className="flex bg-red-50 px-6 py-2.5 rounded-full gap-2 border border-red-100">
                                                    {[...Array(review.rating)].map((_, i) => (
                                                        <Star key={i} className="h-5 w-5 fill-red-600 text-red-600 drop-shadow-sm" />
                                                    ))}
                                                </div>
                                            </div>

                                            <div className="bg-gray-50 p-12 rounded-[3.5rem] relative border border-gray-50 shadow-inner">
                                                <Sparkles className="absolute -top-6 -right-6 h-16 w-16 text-red-600/5 group-hover:text-red-600/10 transition-colors" />
                                                <p className="text-gray-950 font-black text-2xl md:text-3xl leading-tight italic">
                                                    "{review.review_text}"
                                                </p>
                                            </div>

                                            <div className="flex items-center gap-6">
                                                <Badge className="bg-gray-950 text-white border-0 shadow-xl">NFC_SECURE</Badge>
                                                <Badge className="bg-red-600 text-white border-0 shadow-xl">AI_TRANSCRIPE</Badge>
                                            </div>
                                        </div>

                                        {/* Right: AI Response Area */}
                                        <div className="space-y-10 border-t lg:border-t-0 lg:border-l-[12px] pt-16 lg:pt-0 lg:pl-20 border-gray-50 group-hover:border-red-600 transition-all duration-700">
                                            <div className="flex items-center justify-between">
                                                <h4 className="text-[11px] font-black text-gray-400 uppercase tracking-[0.5em] flex items-center gap-4 italic leading-none">
                                                    <Bot className="h-4 w-4 text-red-600" />
                                                    AI INTEL RESPONSE
                                                </h4>
                                                {review.auto_reply_text && (
                                                    <Button variant="ghost" size="sm" onClick={() => handleCopy(review.auto_reply_text!)} className="h-10 px-6 text-red-600 font-black text-[10px] uppercase tracking-[0.4em] hover:bg-red-50 rounded-full border border-red-50 italic">
                                                        <Copy className="h-3 w-3 mr-3" /> Copy Stream
                                                    </Button>
                                                )}
                                            </div>

                                            {review.auto_reply_text ? (
                                                <div className="bg-red-50/30 border-4 border-red-100 p-12 rounded-[3.5rem] relative animate-in zoom-in duration-500 shadow-3xl">
                                                    <p className="text-red-950 font-black leading-tight italic text-2xl md:text-3xl">
                                                        "{review.auto_reply_text}"
                                                    </p>
                                                </div>
                                            ) : (
                                                <div className="h-64 bg-gray-50 border-4 border-dashed border-gray-200 rounded-[4rem] flex flex-col items-center justify-center p-10 text-center group/empty shadow-inner">
                                                    <Languages className="h-12 w-12 text-gray-200 mb-6 group-hover/empty:scale-125 transition-transform" />
                                                    <p className="text-xs font-black text-gray-400 uppercase tracking-[0.5em] max-w-[250px] italic leading-relaxed">
                                                        Transmission awaits response generation.
                                                    </p>
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        className="mt-10 bg-white border-4 border-red-600 text-red-600 hover:bg-red-600 hover:text-white h-16 px-12 rounded-full font-black uppercase tracking-[0.4em] text-[10px] shadow-2xl transition-all"
                                                        disabled={generatingFor === review.id}
                                                    >
                                                        {generatingFor === review.id ? <Loader2 className="h-6 w-6 animate-spin" /> : 'EXECUTE GEN-REPLY'}
                                                    </Button>
                                                </div>
                                            )}

                                            {review.auto_reply_text && (
                                                <div className="flex justify-start pt-4">
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        variant="ghost"
                                                        className="text-gray-400 hover:text-red-600 font-black text-[10px] uppercase tracking-[0.4em] rounded-2xl hover:bg-red-50 h-10 px-6 italic transition-all"
                                                    >
                                                        <HistoryIcon className="h-4 w-4 mr-3" /> Re-Sync Logic
                                                    </Button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))
                    )}
                </div>
            </main>

            {/* Sticky Bottom Status - Editorial scale */}
            <div className="fixed bottom-10 left-1/2 -translate-x-1/2 bg-gray-950 text-white px-12 py-8 rounded-[3rem] shadow-[0_60px_120px_-20px_rgba(0,0,0,0.5)] border-4 border-white/5 backdrop-blur-2xl flex items-center gap-12 z-50 skew-x-[-5deg]">
                <div className="flex flex-col">
                    <span className="text-[10px] font-black text-red-600 uppercase tracking-[0.6em] italic mb-1.5">INTEL_STATUS</span>
                    <span className="text-sm font-black font-mono tracking-tighter italic">CORE: ACTIVE_GROQ_SYNAPSE</span>
                </div>
                <div className="w-[2px] h-12 bg-white/10"></div>
                <div className="flex items-center gap-4">
                    <div className="w-4 h-4 bg-red-600 rounded-full animate-pulse shadow-[0_0_20px_rgba(220,38,38,0.8)]"></div>
                    <span className="text-sm font-black uppercase tracking-[0.5em] italic">SYSTEM_READY</span>
                </div>
            </div>

            {/* Language Toggle Fixed Bottom Right */}
            <div className="fixed bottom-12 right-12 z-[100] transform hover:scale-125 transition-all duration-500 group">
                <div className="absolute inset-0 bg-red-600 blur-[40px] opacity-0 group-hover:opacity-30 transition-opacity rounded-full"></div>
                <div className="bg-white p-4 rounded-full shadow-[0_50px_100px_rgba(220,38,38,0.4)] border-4 border-red-50 relative z-10 transition-transform">
                    <LanguageToggle />
                </div>
            </div>
        </div>
    );
}

const Badge = ({ children, className }: { children: React.ReactNode, className?: string }) => (
    <div className={`px-6 py-2.5 rounded-full text-[10px] font-black uppercase tracking-[0.4em] shadow-2xl skew-x-[-10deg] italic ${className}`}>
        {children}
    </div>
);
