import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import {
    ArrowLeft, Loader2, MessageSquare, Star,
    Bot, Copy, Check, Sparkles, Wand2, History as HistoryIcon,
    Trash2, Search, Filter, Languages, Target, ShieldCheck
} from 'lucide-react';
import { generateAutoReply } from '@/services/gemini';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import { LanguageToggle } from '@/components/LanguageToggle';

interface Review {
    id: string;
    rating: number;
    review_text: string | null;
    customer_name: string | null;
    created_at: string;
    auto_reply_text?: string | null;
    metadata?: any;
}

export default function ReviewManagement() {
    const navigate = useNavigate();
    const { t, i18n } = useTranslation();
    const [reviews, setReviews] = useState<Review[]>([]);
    const [loading, setLoading] = useState(true);
    const [generatingFor, setGeneratingFor] = useState<string | null>(null);

    useEffect(() => {
        fetchReviews();
    }, []);

    const fetchReviews = async () => {
        try {
            setLoading(true);
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            const { data, error } = await (supabase as any)
                .from('analytics_logs')
                .select('*')
                .eq('event_type', 'review_click')
                .order('created_at', { ascending: false });

            if (error) throw error;

            const formattedReviews = data.map((item: any) => ({
                id: item.id,
                rating: item.metadata?.rating || 5,
                review_text: item.metadata?.suggestion || 'Positive review generated by AI',
                customer_name: 'Customer',
                created_at: item.created_at,
                metadata: item.metadata,
                auto_reply_text: item.metadata?.auto_reply
            }));

            setReviews(formattedReviews);
        } catch (error) {
            console.error('Error fetching reviews:', error);
            toast.error('Review detection failure');
        } finally {
            setLoading(false);
        }
    };

    const handleGenerateReply = async (review: Review) => {
        setGeneratingFor(review.id);
        try {
            const reply = await generateAutoReply(
                review.review_text || 'Excellent service',
                review.rating,
                'Our Business',
                i18n.language
            );

            await (supabase as any)
                .from('analytics_logs')
                .update({
                    metadata: {
                        ...review.metadata,
                        auto_reply: reply
                    }
                })
                .eq('id', review.id);

            toast.success('AI Auto-Reply Generated!');
            setReviews(prev => prev.map(r => r.id === review.id ? { ...r, auto_reply_text: reply } : r));
        } catch (error) {
            console.error('Reply generation failed:', error);
            toast.error('AI Processing failure');
        } finally {
            setGeneratingFor(null);
        }
    };

    const handleCopy = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success('Reply ready in clipboard');
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-white">
                <Loader2 className="h-10 w-10 animate-spin text-red-600" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white font-inter">
            {/* Premium Header */}
            <header className="bg-white/95 backdrop-blur-md border-b sticky top-0 z-50">
                <div className="container mx-auto px-4 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" onClick={() => navigate("/dashboard")} className="text-gray-400 hover:text-red-600 rounded-full h-10 px-6 font-black uppercase tracking-widest text-[10px]">
                            <ArrowLeft className="h-4 w-4 mr-2" />
                            Exit Hub
                        </Button>
                        <div className="flex items-center gap-2">
                            <div className="bg-red-600 p-2.5 rounded-xl shadow-lg shadow-red-200">
                                <Bot className="h-5 w-5 text-white" />
                            </div>
                            <h1 className="text-xl font-black text-gray-900 tracking-tighter uppercase">AI Auto-Reply HUB</h1>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <LanguageToggle />
                        <div className="h-8 w-px bg-gray-100 mx-2"></div>
                        <img src="/logo.jpg" alt="Logo" className="h-10 w-auto object-contain hidden sm:block rounded-md shadow-sm" />
                    </div>
                </div>
            </header>

            <main className="container mx-auto px-4 py-12 max-w-6xl">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-12">
                    <div>
                        <h2 className="text-4xl font-black text-gray-900 uppercase tracking-tighter">Response Center</h2>
                        <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-1">Autonomous Reputation Agent Management</p>
                    </div>
                    <div className="flex items-center gap-4 w-full md:w-auto">
                        <Button variant="outline" onClick={fetchReviews} className="flex-1 md:flex-none border-gray-200 h-14 rounded-2xl px-10 font-black uppercase tracking-widest text-[10px] hover:bg-red-50 hover:text-red-600 transition-all">
                            <HistoryIcon className="h-4 w-4 mr-2" />
                            Sync Activity
                        </Button>
                    </div>
                </div>

                <div className="space-y-10">
                    {reviews.length === 0 ? (
                        <div className="py-40 text-center bg-gray-50/50 rounded-[4rem] border-4 border-dashed border-gray-100">
                            <div className="w-24 h-24 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-8">
                                <MessageSquare className="h-10 w-10 text-red-100" />
                            </div>
                            <h3 className="text-xl font-black text-gray-400 uppercase tracking-widest">No Intelligence Logs</h3>
                            <p className="text-[10px] font-bold text-gray-300 uppercase tracking-[0.2em] mt-2">Activity will appear once customers scan your QR cards</p>
                        </div>
                    ) : (
                        reviews.map((review) => (
                            <Card key={review.id} className="border-0 shadow-[0_50px_100px_-20px_rgba(0,0,0,0.05)] rounded-[3rem] overflow-hidden bg-white hover:scale-[1.01] transition-all group">
                                <div className="h-2 bg-red-600 w-full"></div>
                                <CardContent className="p-10 md:p-12">
                                    <div className="flex flex-col lg:flex-row gap-12">
                                        {/* Left: Intent Audit */}
                                        <div className="flex-1 space-y-6">
                                            <div className="flex items-center justify-between border-b border-gray-50 pb-6">
                                                <div className="flex items-center gap-4">
                                                    <div className="w-12 h-12 bg-gray-900 text-white rounded-2xl flex items-center justify-center font-black text-xl">
                                                        C
                                                    </div>
                                                    <div>
                                                        <p className="font-black text-gray-900 uppercase tracking-tight text-sm">Verified External Scan</p>
                                                        <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest leading-none mt-1">{new Date(review.created_at).toLocaleDateString()}</p>
                                                    </div>
                                                </div>
                                                <div className="flex bg-red-50 px-4 py-2 rounded-full gap-1 border border-red-100">
                                                    {[...Array(review.rating)].map((_, i) => (
                                                        <Star key={i} className="h-3.5 w-3.5 fill-red-600 text-red-600" />
                                                    ))}
                                                </div>
                                            </div>

                                            <div className="bg-gray-50 p-8 rounded-[2rem] relative group-hover:bg-red-50/20 transition-colors">
                                                <Target className="absolute -top-4 -right-4 h-12 w-12 text-red-600/5 group-hover:text-red-600/10" />
                                                <p className="text-gray-900 font-bold leading-relaxed text-lg">
                                                    "{review.review_text}"
                                                </p>
                                            </div>

                                            <div className="flex items-center gap-3">
                                                <div className="bg-gray-900 text-white px-4 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest shadow-lg">NFC VERIFIED</div>
                                                <div className="bg-red-600 text-white px-4 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest shadow-lg">AI ASSISTED</div>
                                            </div>
                                        </div>

                                        {/* Right: Response Logic */}
                                        <div className="flex-1 space-y-6 border-t lg:border-t-0 lg:border-l border-gray-100 pt-12 lg:pt-0 lg:pl-12">
                                            <div className="flex items-center justify-between">
                                                <div className="flex items-center gap-2">
                                                    <Sparkles className="h-4 w-4 text-red-600" />
                                                    <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Strategy Formulation</h4>
                                                </div>
                                                {review.auto_reply_text && (
                                                    <Button variant="ghost" size="sm" onClick={() => handleCopy(review.auto_reply_text!)} className="h-10 px-6 bg-red-50 text-red-600 font-black text-[10px] uppercase tracking-widest rounded-xl hover:bg-red-600 hover:text-white transition-all">
                                                        <Copy className="h-3 w-3 mr-2" /> Copy Export
                                                    </Button>
                                                )}
                                            </div>

                                            {review.auto_reply_text ? (
                                                <div className="bg-white border-4 border-red-50 p-8 rounded-[2.5rem] relative shadow-inner group-hover:border-red-100 transition-colors">
                                                    <p className="text-gray-900 font-black leading-relaxed italic text-lg">
                                                        "{review.auto_reply_text}"
                                                    </p>
                                                </div>
                                            ) : (
                                                <div className="h-48 bg-gray-50/50 border-2 border-dashed border-gray-100 rounded-[2.5rem] flex flex-col items-center justify-center p-8 text-center group-hover:bg-red-50/10 transition-colors">
                                                    <Languages className="h-10 w-10 text-gray-100 mb-4" />
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        className="bg-gray-900 hover:bg-red-600 text-white h-14 px-10 rounded-2xl font-black uppercase tracking-widest text-[10px] shadow-xl active:scale-95 transition-all"
                                                        disabled={generatingFor === review.id}
                                                    >
                                                        {generatingFor === review.id ? <Loader2 className="h-5 w-5 animate-spin" /> : 'Formulate Response'}
                                                    </Button>
                                                </div>
                                            )}

                                            {review.auto_reply_text && (
                                                <div className="flex justify-end pt-2">
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        variant="ghost"
                                                        className="text-gray-400 font-black text-[10px] uppercase tracking-widest rounded-xl hover:text-red-600 hover:bg-red-50 transition-all px-6 py-4"
                                                    >
                                                        <HistoryIcon className="h-4 w-4 mr-2" /> Re-formulate Strategy
                                                    </Button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))
                    )}
                </div>
            </main>

            {/* System Status Strip */}
            <div className="fixed bottom-8 left-1/2 -translate-x-1/2 bg-gray-950 p-1 rounded-full shadow-[0_30px_60px_-15px_rgba(0,0,0,0.3)] z-50">
                <div className="flex items-center gap-6 px-10 py-3">
                    <div className="flex items-center gap-3">
                        <div className="w-2.5 h-2.5 bg-red-600 rounded-full animate-pulse shadow-[0_0_15px_rgba(220,38,38,0.8)]"></div>
                        <span className="text-[10px] font-black text-white uppercase tracking-[0.2em]">Agent Hub: Operational</span>
                    </div>
                    <div className="w-px h-4 bg-white/10"></div>
                    <div className="flex items-center gap-2">
                        <ShieldCheck className="h-3.5 w-3.5 text-red-600" />
                        <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Precision AI Systems</span>
                    </div>
                </div>
            </div>

            <footer className="py-20 text-center border-t border-gray-50 mt-20">
                <img src="/logo.jpg" alt="Logo" className="h-10 w-auto mx-auto mb-4 opacity-30" />
                <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">© 2026 Creative Mark AI Technologies</p>
            </footer>
        </div>
    );
}
