import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import {
    ArrowLeft, Loader2, MessageSquare, Star,
    Bot, Copy, Check, Sparkles, Wand2, History,
    Trash2, Search, Filter, Languages
} from 'lucide-react';
import { generateAutoReply } from '@/services/gemini';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import { LanguageToggle } from '@/components/LanguageToggle';

interface Review {
    id: string;
    rating: number;
    review_text: string | null;
    customer_name: string | null;
    created_at: string;
    auto_reply_text?: string | null;
    metadata?: any;
}

export default function ReviewManagement() {
    const navigate = useNavigate();
    const { t, i18n } = useTranslation();
    const [reviews, setReviews] = useState<Review[]>([]);
    const [loading, setLoading] = useState(true);
    const [generatingFor, setGeneratingFor] = useState<string | null>(null);

    useEffect(() => {
        fetchReviews();
    }, []);

    const fetchReviews = async () => {
        try {
            setLoading(true);
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) return;

            // We'll fetch from analytics_logs where event_type is 'review_click'
            // These represent reviews the AI generated and customer likely posted
            const { data, error } = await (supabase as any)
                .from('analytics_logs')
                .select('*')
                .eq('event_type', 'review_click')
                .order('created_at', { ascending: false });

            if (error) throw error;

            const formattedReviews = data.map((item: any) => ({
                id: item.id,
                rating: item.metadata?.rating || 5,
                review_text: item.metadata?.suggestion || 'Positive review generated by AI',
                customer_name: 'Customer', // Metadata doesn't usually have name unless we capture it
                created_at: item.created_at,
                auto_reply_text: item.metadata?.auto_reply // Check if we already generated one
            }));

            setReviews(formattedReviews);
        } catch (error) {
            console.error('Error fetching reviews:', error);
            toast.error('Failed to load reviews');
        } finally {
            setLoading(false);
        }
    };

    const handleGenerateReply = async (review: Review) => {
        setGeneratingFor(review.id);
        try {
            const reply = await generateAutoReply(
                review.review_text || 'Excellent service',
                review.rating,
                'Our Business',
                i18n.language
            );

            // Save reply to metadata
            await (supabase as any)
                .from('analytics_logs')
                .update({
                    metadata: {
                        ...review.metadata,
                        auto_reply: reply
                    }
                })
                .eq('id', review.id);

            toast.success('AI Auto-Reply Generated!');
            setReviews(prev => prev.map(r => r.id === review.id ? { ...r, auto_reply_text: reply } : r));
        } catch (error) {
            console.error('Reply generation failed:', error);
            toast.error('Failed to generate reply');
        } finally {
            setGeneratingFor(null);
        }
    };

    const handleCopy = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success('Copied to clipboard!');
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-white">
                <Loader2 className="h-10 w-10 animate-spin text-red-600" />
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-50/50 pb-20 font-inter">
            {/* Premium Header */}
            <header className="bg-white border-b sticky top-0 z-50">
                <div className="container mx-auto px-4 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" onClick={() => navigate("/dashboard")} className="hover:bg-red-50 text-gray-600 hover:text-red-600 rounded-xl">
                            <ArrowLeft className="h-5 w-5" />
                        </Button>
                        <div className="flex items-center gap-2">
                            <div className="bg-red-600 p-2.5 rounded-xl shadow-lg shadow-red-200">
                                <Bot className="h-5 w-5 text-white" />
                            </div>
                            <h1 className="text-xl font-black text-gray-900 tracking-tight uppercase">AI Auto-Reply Hub</h1>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        <LanguageToggle />
                        <img src="/logo.jpg" alt="Logo" className="h-10 w-auto object-contain hidden sm:block" />
                    </div>
                </div>
            </header>

            <main className="container mx-auto px-4 py-10 max-w-5xl">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
                    <div>
                        <h2 className="text-3xl font-black text-gray-900 uppercase tracking-tighter">Review Management</h2>
                        <p className="text-sm font-bold text-gray-400 uppercase tracking-widest mt-1">Generate professional AI responses instantly</p>
                    </div>
                    <div className="flex items-center gap-3 w-full md:w-auto">
                        <Button variant="outline" className="flex-1 md:flex-none border-gray-200 shadow-sm rounded-xl py-6 hover:bg-white font-bold uppercase tracking-widest text-[10px]">
                            <Search className="h-4 w-4 mr-2" />
                            Search
                        </Button>
                        <Button onClick={fetchReviews} className="flex-1 md:flex-none bg-red-600 hover:bg-red-700 text-white rounded-xl py-6 shadow-xl shadow-red-200 font-bold uppercase tracking-widest text-[10px]">
                            <Wand2 className="h-4 w-4 mr-2" />
                            Refresh
                        </Button>
                    </div>
                </div>

                <div className="space-y-8">
                    {reviews.length === 0 ? (
                        <Card className="border-4 border-dashed border-gray-100 rounded-3xl py-32 text-center bg-transparent">
                            <div className="flex flex-col items-center gap-4 opacity-30">
                                <MessageSquare className="h-12 w-12" />
                                <p className="font-black uppercase tracking-[0.2em] text-xs">No reviews detected yet</p>
                            </div>
                        </Card>
                    ) : (
                        reviews.map((review) => (
                            <Card key={review.id} className="border-0 shadow-2xl rounded-3xl overflow-hidden bg-white hover:shadow-red-500/5 transition-all animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="p-1 bg-gradient-to-r from-red-600 to-red-400"></div>
                                <CardContent className="p-8">
                                    <div className="flex flex-col lg:flex-row gap-10">
                                        {/* Left: Customer Review Info */}
                                        <div className="flex-1 space-y-4">
                                            <div className="flex items-center justify-between">
                                                <div className="flex items-center gap-3">
                                                    <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center font-black text-gray-400">
                                                        C
                                                    </div>
                                                    <div>
                                                        <p className="font-black text-gray-900 uppercase tracking-tight">Verified Customer</p>
                                                        <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{new Date(review.created_at).toLocaleDateString()}</p>
                                                    </div>
                                                </div>
                                                <div className="flex bg-amber-50 px-3 py-1 rounded-full gap-1">
                                                    {[...Array(review.rating)].map((_, i) => (
                                                        <Star key={i} className="h-3.5 w-3.5 fill-amber-500 text-amber-500" />
                                                    ))}
                                                </div>
                                            </div>

                                            <div className="bg-gray-50 p-6 rounded-2xl relative">
                                                <Sparkles className="absolute -top-3 -right-3 h-8 w-8 text-red-500/10" />
                                                <p className="text-gray-700 font-bold leading-relaxed">
                                                    "{review.review_text}"
                                                </p>
                                            </div>

                                            <div className="flex items-center gap-3">
                                                <Badge className="bg-green-50 text-green-600 border-0">NFC TAP</Badge>
                                                <Badge className="bg-blue-50 text-blue-600 border-0">AI ASSISTED</Badge>
                                            </div>
                                        </div>

                                        {/* Middle: AI Response Area */}
                                        <div className="flex-1 space-y-4 border-l-0 lg:border-l lg:pl-10 border-gray-100">
                                            <div className="flex items-center justify-between">
                                                <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] flex items-center gap-2">
                                                    <Bot className="h-3 w-3 text-red-500" />
                                                    AI Suggested Response
                                                </h4>
                                                {review.auto_reply_text && (
                                                    <Button variant="ghost" size="sm" onClick={() => handleCopy(review.auto_reply_text!)} className="h-8 text-blue-600 font-bold text-[10px] uppercase tracking-widest hover:bg-blue-50">
                                                        <Copy className="h-3 w-3 mr-1" /> Copy Reply
                                                    </Button>
                                                )}
                                            </div>

                                            {review.auto_reply_text ? (
                                                <div className="bg-red-50/50 border-2 border-red-100 p-6 rounded-2xl relative animate-in zoom-in duration-300">
                                                    <p className="text-red-900 font-bold leading-relaxed italic">
                                                        "{review.auto_reply_text}"
                                                    </p>
                                                </div>
                                            ) : (
                                                <div className="h-40 bg-gray-50 border-2 border-dashed border-gray-200 rounded-3xl flex flex-col items-center justify-center p-6 text-center">
                                                    <Languages className="h-8 w-8 text-gray-200 mb-2" />
                                                    <p className="text-xs font-black text-gray-300 uppercase tracking-widest max-w-[200px]">
                                                        No response generated for this review.
                                                    </p>
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        className="mt-4 bg-white border-2 border-red-600 text-red-600 hover:bg-red-50 h-10 px-6 rounded-full font-black uppercase tracking-widest text-[10px]"
                                                        disabled={generatingFor === review.id}
                                                    >
                                                        {generatingFor === review.id ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Generate Now'}
                                                    </Button>
                                                </div>
                                            )}

                                            {review.auto_reply_text && (
                                                <div className="flex justify-end pt-2">
                                                    <Button
                                                        onClick={() => handleGenerateReply(review)}
                                                        variant="ghost"
                                                        className="text-red-600 font-black text-[10px] uppercase tracking-widest rounded-xl hover:bg-red-50"
                                                    >
                                                        <History className="h-3 w-3 mr-1" /> Re-Generate
                                                    </Button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))
                    )}
                </div>
            </main>

            {/* Sticky Bottom Actions */}
            <div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-gray-900 text-white px-8 py-4 rounded-full shadow-2xl border border-white/10 backdrop-blur-md flex items-center gap-8 z-50">
                <div className="flex flex-col">
                    <span className="text-[10px] font-black text-red-500 uppercase tracking-widest">Automation Status</span>
                    <span className="text-xs font-bold font-mono">AI ENGINE: ACTIVE (GROQ-LLAMA)</span>
                </div>
                <div className="w-[1px] h-8 bg-white/10"></div>
                <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                    <span className="text-xs font-black uppercase tracking-widest">System Ready</span>
                </div>
            </div>
        </div>
    );
}

const Badge = ({ children, className }: { children: React.ReactNode, className?: string }) => (
    <div className={`px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-widest shadow-sm ${className}`}>
        {children}
    </div>
);
