// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fallback to prevent app crash during development without creds
let url = SUPABASE_URL || 'https://placeholder.supabase.co';
const key = SUPABASE_KEY || 'placeholder-key';

// Validate URL format (must be absolute with http/https)
try {
  new URL(url);
} catch (e) {
  console.warn('Invalid Supabase URL provided. Using fallback.');
  url = 'https://placeholder.supabase.co';
}

if (!SUPABASE_URL || !SUPABASE_KEY || SUPABASE_URL === 'your-supabase-url') {
  console.warn('Supabase credentials missing or default in .env. Some features may not work.');
  // Ensure we consistently use fallback for default placeholders to avoid crashes
  if (url === 'your-supabase-url') url = 'https://placeholder.supabase.co';
}

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});